steps:
  - name: gradle:8.4-jdk17
    entrypoint: gradle
    args:
      - clean
      - build
      - shadowJar
artifacts:
  objects:
    location: ${_JAR_GCS_LOCATION}
    paths:
      - build/libs/auto-data-tokenize-all.jar